config/routes.rb
Rails.application.routes.draw do

  resources :blogs, only: :index

  get "/home", to: "home#map"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController


  def index
   puts "adsaasda"
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController


  def map

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blogs/index.html.erb
<div class="container">

</div>

app/views/home/explorer.html.erb
<div class="container">
    <div>
        <h1>TESTE</h1>
    </div>
</div>

app/views/home/map.html.erb
<!--

  <div >
    <div  id="map_canvas" style="position: absolute; width:100%; height:100%;"></div>
  </div>
  -->

<%= javascript_include_tag "controllers/home" %>
<script src='//maps.googleapis.com/maps/api/js?sensor=false'></script>
<div id="teste" ng-controller="HomeController">
  <ui-gmap-google-map center="map.center" zoom="map.zoom" options="options"></ui-gmap-google-map>
</div>

<div style="position:fixed; bottom:0; width:100%; height: 100px; background-color: rgba(0,0,0,0.8);">
  <div class="fb-like-box" data-href="https://www.facebook.com/pages/Olha-o-Rol&#xea;/722573154430808" data-width="100%" data-height="100" data-colorscheme="dark" data-show-faces="true" data-header="false" data-stream="false" data-show-border="true"></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-br">
<head>

	
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Olha o Rolê</title>

    <%= stylesheet_link_tag "application" %>
    <!--[if lt IE 9]>
	    <script src="js/html5shiv.js"></script>
	    <script src="js/respond.min.js"></script>
    <![endif]-->
  <%= favicon_link_tag "favicon.ico" %>
   <!--
    <%= image_tag "ico/apple-touch-icon-144-precomposed.png" %>
    <%= image_tag "ico/apple-touch-icon-114-precomposed.png" %>
    <%= image_tag "ico/apple-touch-icon-72-precomposed.png" %>
    <%= image_tag "ico/apple-touch-icon-144-precomposed.png" %>
    <%= image_tag "ico/apple-touch-icon-57-precomposed.png" %>


  -->
  <style type="text/css">
      html { height: 100% }
      body { height: 100%; margin: 0; padding: 0 }
      #map_canvas { height: 100% }
  </style>
<!--
  <script type="text/javascript"
          src="http://maps.googleapis.com/maps/api/js?key=AIzaSyDRVpqN5PTvDQmC26pX5yQtBv2t3YGCUcs&sensor=false">
  </script>-->

</head><!--/head-->

<body ng-app="app">

	<header id="navigation">      
        <div class="navbar navbar-fixed-top" role="banner">
            <div class="container">
            	<div class="row">
            		<div class="col-sm-3">
            			<div class="navbar-header">
		                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
		                        <span class="sr-only">Toggle navigation</span>
		                        <span class="icon-bar"></span>
		                        <span class="icon-bar"></span>
		                        <span class="icon-bar"></span>
		                    </button>
                          <%= link_to image_tag "logo 1.1.png" , controller: "home", action: "map" %>
		                </div>
            		</div>
            		<div class="col-sm-9" >
            			<nav class="navbar-right collapse navbar-collapse">
		                    <ul class="nav navbar-nav">                                                                     
		                        <li>
                                  <%= link_to "Início", home_path %>
                                </li>
		                        <li>
                                  <%= link_to "Blog", blogs_path %>
		                        </li>                         
		                        <li class="dropdown"><a href="#">Event<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="latest-events.html">Events List</a></li>
                                        <li><a href="single-event.html">Single Event</a></li>
                                    </ul>
                                </li>
		                        <li><a href="album.html">Album</a></li>                     
		                        <li class="dropdown"><a href="#">Blog<i class="fa fa-angle-down"></i></a>
                                    <ul role="menu" class="sub-menu">
                                        <li><a href="blog.html">Blog List</a></li>
                                        <li><a href="single.html">Single Post</a></li>
                                    </ul>
                                </li>
		                        <li><a href="pricing-table.html">Price </a></li>
		                        <li><a href="contact-us.html">Contact </a></li>                               
		                    </ul>
		                </nav>
            		</div>
            	</div> 
            </div>
        </div>
    </header> <!--/#navigation-->

<%= yield %>

    <%= javascript_include_tag "application" %>
    <script type="text/javascript">
        jQuery(document).ready(function($){
            $(window).load(function() {
                // The slider being synced must be initialized first
                $('#carousel').flexslider({
                    animation: "slide",
                    controlNav: false,
                    animationLoop: false,
                    slideshow: false,
                    itemWidth: 41,
                    itemMargin: 0,
                    asNavFor: '#slider'
                });

                $('#slider').flexslider({
                    directionNav: false,
                    animation: "fade",
                    controlNav: false,
                    animationLoop: false,
                    slideshow: false,
                    sync: "#carousel"
                });
            });
        });

    </script>

    <div id="fb-root"></div>
    <script>(function(d, s, id) {
        var js, fjs = d.getElementsByTagName(s)[0];
        if (d.getElementById(id)) return;
        js = d.createElement(s); js.id = id;
        js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
        fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));

    </script>


</body>
</html>